COMPONENT=sdC
#PFLAGS += -DNO_SD

OPTFLAGS = -ggdb -Os -fnesc-no-inline
PFLAGS += -Wno-unused-but-set-variable -Wno-unused-variable

TINYOS_ROOT_DIR ?= ../..
include $(TINYOS_ROOT_DIR)/Makefile.include
