
/*
 * code auto-generated by wds_prep.py
*/

#include <stdint.h>
#include "Si446x_CustomPacketRX_wPSM.h"
uint8_t const SI446X_CUSTOMPACKETRX_WPSM_config[] = SI446X_CUSTOMPACKETRX_WPSM_DATA_ARRAY;
uint8_t const SI446X_CUSTOMPACKETRX_WPSM_name[]   = SI446X_CUSTOMPACKETRX_WPSM_NAME;
