
/*
 * code auto-generated by wds_prep.py
*/

#include <stdint.h>
#include "Si4468_100b_433m_200khz_psm.h"
uint8_t const SI4468_100B_433M_200KHZ_PSM_config[] = SI4468_100B_433M_200KHZ_PSM_DATA_ARRAY;
uint8_t const SI4468_100B_433M_200KHZ_PSM_name[]   = SI4468_100B_433M_200KHZ_PSM_NAME;
