
/*
 * code auto-generated by wds_prep.py
*/

#include <stdint.h>
#include "Si4468_10kb_433m_200khz.h"
uint8_t const SI4468_10KB_433M_200KHZ_config[] = SI4468_10KB_433M_200KHZ_DATA_ARRAY;
uint8_t const SI4468_10KB_433M_200KHZ_name[]   = SI4468_10KB_433M_200KHZ_NAME;
