/**
 * Copyright @ 2016 Dan Maltbie
 * @author Dan Maltbie
 * All rights reserved.
 */

#include "trace.h"
#include "panic.h"
#include <si446x.h>

#ifndef PANIC_RADIO
enum {
  __panic_radio = unique(UQ_PANIC_SUBSYS)
};

#define PANIC_RADIO __panic_radio
#endif

/**************************************************************************/
/*
 * Configuration Parameters
 *
 * Two major classes.  The first is static and is generated
 * by the EZ Radio Pro program based on various input parameters.
 * Static WDS parameters are exported via the radio_config_si446x.h
 * file via the simple byte define SI446X_WDS_CONFIG_BYTES.
 *
 * The second class are those parameters that are either h/w dependent
 * or are protocol/packet format dependent or are driver dependent.  These are
 * called "local" properties.  These are defined below.
 *
 * Both si446x_wds_config and si446x_local_config are simple byte arrays.
 * Each entry starts with the length of the following command, followed by
 * command bytes.  The array is terminated by a zero length.
 */

/* configuration generated by the WDS3 program
*/
const uint8_t si446x_wds_config[] = SI446X_WDS_CONFIG_BYTES;


/**************************************************************************/

/*  ---  Local Config ---
 *
 * Driver/Platform dependent
 *
 * SI446X_GPIO_PIN_CFG_LEN and SI446X_RF_GPIO_PIN_CFG are provided by platform
 * dependent code and are in radio_platform_si446x.h.  See platform code,
 * tos/platform/<platform>/hardware/si446x/...
 */

/*
 * GLOBAL_CONFIG:(p0003), sequencer_mode (FAST), fifo_mode (HALF_DUPLEX FIFO)
 *     protocol (0, GENERIC), power_mode (0, HIGH_PERF).
 *
 * fifo_mode HALF_DUPLEX yields a unified 129 byte fifo.
 * 0003 <- 0x60, split fifo,   empty_tx_len 64
 * 0003 <- 0x70, unified fifo, empty_tx_len 129
 */
#define SI446X_GLOBAL_CONFIG_1_LEN      5
#define SI446X_GLOBAL_CONFIG_1          0x11, 0x00, 0x01, 0x03, 0x60

/* interrupt enable (p0100)
 * enable selected interrupts
 */
#define SI446X_INT_CTL_ENABLE_4_LEN     8
#define SI446X_INT_CTL_ENABLE_4         0x11, 0x01, 0x04, 0x00,  \
                                        SI446X_INT_STATUS_MODEM_INT_STATUS + SI446X_INT_STATUS_PH_INT_STATUS,  \
                                        SI446X_PH_INTEREST, SI446X_MODEM_INTEREST, SI446X_CHIP_INTEREST


/*
 * PREAMBLE: (p1000+)
 *
 * TX_LENGTH:   8 bytes (64bits)
 * CONFIG_STD_1:RX_THRESH (0x14) 20 bits, do not skip SYNC
 * CONFIG_NSTD: not used, 0x00
 * CONFIG_STD_2: TIMEOUT_EXTENDED 0, TIMEOUT: 0xf 60 bit time out
 * PREAMBLE_CONFIG: 0x31, 1 tx first, tx_length in bytes, no manchester, pre_1010
 */
#define SI446X_PREAMBLE_LEN             9
#define SI446X_PREAMBLE                 0x11, 0x10, 0x09, 0x00, 0x08, 0x14, 0x00, 0x0f, 0x31

/*
 * Various Pkt configs: (p1200+)
 *
 * CRC_CONFIG: 0x85, CRC_SEED, POLY 5 CCITT_16
 * various whitening
 * CONFIG1: 0x82, PH_FIELD_SPLIT, CRC_ENDIAN msb, bit_order msb
 *
 * TX and RX fields are split.  Different field definitions are used for TX
 * and RX.  See documentation on TX and RX at the front of this file.
 */
#define SI446X_PKT_CRC_CONFIG_7_LEN     11
#define SI446X_PKT_CRC_CONFIG_7         0x11, 0x12, 0x07, 0x00, \
                                              0x85, 0x01, 0x08, 0xFF, 0xFF, 0x00, 0x82

#define SI446X_PKT_LEN_5_LEN            9
#define SI446X_PKT_LEN_5                0x11, 0x12, 0x05, 0x08, \
                                              0x2a, 0x01, 0x00, 0x30, 0x30

#define SI446X_PKT_TX_FIELD_CONFIG_6_LEN 10
#define SI446X_PKT_TX_FIELD_CONFIG_6    0x11, 0x12, 0x06, 0x0d, \
                                              0x00, 0x01, 0x04, 0xa2, \
                                              0x00, 0x00

#define SI446X_PKT_RX_FIELD_CONFIG_10_LEN 14
#define SI446X_PKT_RX_FIELD_CONFIG_10   0x11, 0x12, 0x0a, 0x21, \
                                              0x00, 0x01, 0x04, 0x82, \
                                              0x00, 0x81, 0x00, 0x0a, \
                                              0x00, 0x00

/* MODEM_RSSI (p204a+)
 *
 * MODEM_RSSI_THRESH (p204a): set to INITIAL_RSSI_THRESH
 * MODEM_RSSI_JUMP_THRESH:    default 0xc (not used)
 * MODEM_RSSI_CONTROL:        CHECK_THRESH_AT_LATCH 1
 *                            AVERAGE: 0 (updated every bit time, average of 4 bit times)
 *                            LATCH: 5 RX_STATE3, 15 bit times after RX enabled.
 */
#define SI446X_MODEM_RSSI_LEN           7
#define SI446X_MODEM_RSSI               0x11, 0x20, 0x03, 0x4a, SI446X_INITIAL_RSSI_THRESH, \
                                              0x0c, 0x25

/**************************************************************************/

/*
 * Local Config, driver/hw dependent
 */
const uint8_t si446x_local_config[] = {
  SI446X_GPIO_PIN_CFG_LEN,           SI446X_RF_GPIO_PIN_CFG,
  SI446X_GLOBAL_CONFIG_1_LEN,        SI446X_GLOBAL_CONFIG_1,
  SI446X_INT_CTL_ENABLE_4_LEN,       SI446X_INT_CTL_ENABLE_4,
  SI446X_PREAMBLE_LEN,               SI446X_PREAMBLE,
  SI446X_PKT_CRC_CONFIG_7_LEN,       SI446X_PKT_CRC_CONFIG_7,
  SI446X_PKT_LEN_5_LEN,              SI446X_PKT_LEN_5,
  SI446X_PKT_TX_FIELD_CONFIG_6_LEN,  SI446X_PKT_TX_FIELD_CONFIG_6,
  SI446X_PKT_RX_FIELD_CONFIG_10_LEN, SI446X_PKT_RX_FIELD_CONFIG_10,
  SI446X_MODEM_RSSI_LEN,             SI446X_MODEM_RSSI,
  0
};

/**************************************************************************/
/*
 * chip debugging
 */

/* radio pending state trace array
 */
#define  RPS_MAX 64
norace uint16_t rps_next, rps_prev;
norace rps_t    rps[RPS_MAX];

/* specify which radio parameters to dump
 */
const dump_prop_desc_t dump_prop[] = {
  { 0x0000, (void *) &rd.gr00_global,   SI446X_GROUP00_SIZE },
  { 0x0100, (void *) &rd.gr01_int,      SI446X_GROUP01_SIZE },
  { 0x0200, (void *) &rd.gr02_frr,      SI446X_GROUP02_SIZE },
  { 0x1000, (void *) &rd.gr10_preamble, SI446X_GROUP10_SIZE },
  { 0x1100, (void *) &rd.gr11_sync,     SI446X_GROUP11_SIZE },
  { 0x1200, (void *) &rd.gr12_pkt,      SI446X_GROUP12_SIZE },
#ifdef SI446X_GROUP12a_SIZE
  { 0x1221, (void *) &rd.gr12a_pkt,     SI446X_GROUP12a_SIZE },
#endif
  { 0x2000, (void *) &rd.gr20_modem,    SI446X_GROUP20_SIZE },
  { 0x2100, (void *) &rd.gr21_modem,    SI446X_GROUP21_SIZE },
  { 0x2200, (void *) &rd.gr22_pa,       SI446X_GROUP22_SIZE },
  { 0x2300, (void *) &rd.gr23_synth,    SI446X_GROUP23_SIZE },
  { 0x3000, (void *) &rd.gr30_match,    SI446X_GROUP30_SIZE },
  { 0x4000, (void *) &rd.gr40_freq_ctl, SI446X_GROUP40_SIZE },
  { 0x5000, (void *) &rd.gr50_hop,      SI446X_GROUP50_SIZE },
  { 0xF000, (void *) &rd.grF0_pti,      SI446X_GROUPF0_SIZE },
  { 0, NULL, 0 },
};


/* temporary buffer for reading chip state
 */
volatile norace si446x_chip_all_t  chip_debug;


/* rf_frr_ctl_a_mode_4 defines what the four FRR registers return
 * and how they show up in radio_pend
 */
norace uint8_t radio_pend[4];
norace uint8_t radio_pend1[4];

/* temporary buffer for response to send.cmd()
 */
norace uint8_t      rsp[16];

/* array of timing measurements for each possible chip command and property.
 * contains the value measured when last used
 */
norace cmd_timing_t  cmd_timings[256];
norace cmd_timing_t prop_timings[256];


/**************************************************************************/
/*
 * Radio Commands
 */

const uint8_t si446x_part_info[]     = { SI446X_CMD_PART_INFO };    /* 01 */
const uint8_t si446x_power_up[]      = { SI446X_RF_POWER_UP };      /* 02 */
const uint8_t si446x_func_info[]     = { SI446X_CMD_FUNC_INFO };    /* 10 */
const uint8_t si446x_gpio_cfg_nc[]   = { SI446X_CMD_GPIO_PIN_CFG,   /* 13 */
  SI446X_GPIO_NO_CHANGE, SI446X_GPIO_NO_CHANGE,
  SI446X_GPIO_NO_CHANGE, SI446X_GPIO_NO_CHANGE,
  SI446X_GPIO_NO_CHANGE,                /* nirq, no change */
  SI446X_GPIO_NO_CHANGE,                /* sdo, no change */
  0                                     /* gen_config */
};

const uint8_t si446x_fifo_info_nc[]  = { SI446X_CMD_FIFO_INFO, 0 }; /* 15 */

const uint8_t si446x_packet_info_nc[]= { SI446X_CMD_PACKET_INFO };  /* 16 */

const uint8_t si446x_int_status_nc[] = { SI446X_CMD_GET_INT_STATUS, /* 20 */
  SI446X_INT_NO_CLEAR, SI446X_INT_NO_CLEAR, SI446X_INT_NO_CLEAR };

const uint8_t si446x_int_clr[] = { SI446X_CMD_GET_INT_STATUS };     /* 20 */

const uint8_t si446x_ph_status_nc[] = {                             /* 21 */
  SI446X_CMD_GET_PH_STATUS, SI446X_INT_NO_CLEAR };

const uint8_t si446x_ph_clr[] = { SI446X_CMD_GET_PH_STATUS};        /* 21 */

const uint8_t si446x_modem_status_nc[] = {                          /* 22 */
  SI446X_CMD_GET_MODEM_STATUS, SI446X_INT_NO_CLEAR };

const uint8_t si446x_modem_clr[] = { SI446X_CMD_GET_MODEM_STATUS }; /* 22 */

const uint8_t si446x_chip_status_nc[] = {                           /* 23 */
  SI446X_CMD_GET_CHIP_STATUS, SI446X_INT_NO_CLEAR };

const uint8_t si446x_chip_clr[] = { SI446X_CMD_GET_CHIP_STATUS };   /* 23 */

const uint8_t si446x_chip_clr_cmd_err[] = { SI446X_CMD_GET_CHIP_STATUS, 0xf7 };

const uint8_t si446x_device_state[] = { SI446X_CMD_REQUEST_DEVICE_STATE }; /* 33 */

const uint8_t start_rx_short_cmd[] = {  SI446X_CMD_START_RX };

/*
 * len: 0, use variable length in packet
 * rxtimeout_state: 8, stay in rx but rearm.  We make use of the RXTIMEOUT
 *   mechanism provided with RSSI checking.  See MODEM_RSSI_THRESH (p204a).
 * rxvalid_state:   0, stay in rx but do not rearm.
 * rxinvalid_state: 0, stay in rx but do not rearm.
 */
const uint8_t start_rx_cmd[] = {
  SI446X_CMD_START_RX,
  0,                                  /* channel */
  0,                                  /* start immediate */
  0, 0,                               /* len, use variable length */
  //  RC_RX,                              /* rxtimeout, stay, good boy */
  0,                                  /* rxtimeout, stay, good boy */
  0,                                  /* rxvalid */
  0,                                  /* rxinvalid */
};

/*
 * FRR_CTL_A_MODE (p0200)
 *
 * frr is set manually right after POWER_UP
 *
 * A: device state
 * B: PH_PEND
 * C: MODEM_PEND
 * D: Latched_RSSI
 *
 * We use LR (Latched_RSSI) when receiving a packet.  The RSSI value is
 * attached to the last RX packet.  The Latched_RSSI value may (depending on
 * configuration, be associated with some number of bit times once RX is enabled
 * or when SYNC is detected.
 */
const uint8_t si446x_frr_config[] = { 0x11, 0x02, 0x04, 0x00,
				      0x09, 0x04, 0x06, 0x0a
                                    };



/**************************************************************************/
/*
 * MODULE DECLARATION
 */
module Si446xCmdP {
  provides {
    interface Si446xCmd;
  }
  uses {
    interface LocalTime<TRadio>;

    interface FastSpiByte;
    interface SpiByte;
    interface SpiBlock;

    interface Si446xInterface as HW;

    interface Platform;
    interface Trace;
    interface Panic;
  }
}

/**************************************************************************/
/*
 * IMPLEMENTATION
 */
implementation {
#define __PANIC_RADIO(where, w, x, y, z) do {		  \
    call Panic.panic(PANIC_RADIO, where, w, x, y, z);	  \
  } while (0);

  /**************************************************************************/
  /*
   * CCA: note!  The SiLabs folks flip the sense of CCA.  CCA for them
   * is true if the channel is busy.  Other folks (the reasonable ones)
   * consider CCA TRUE if the channel is clear.  We handle this in check_CCA().
   *
   * si446x_cca_threshold is where we hold the value we program the h/w
   * RSSI_THRESHOLD.  We use it to compare received RSSI values to determine
   * whether the channel is busy.
   */
  uint8_t si446x_cca_threshold = SI446X_INITIAL_RSSI_THRESH;



  /**************************************************************************/
  /*
   * ll_si446x_get_sw_cts
   *
   * get the status of the chip CTS by SPI command rather than hardware pin
   *
   */
  uint8_t ll_si446x_get_sw_cts() {
    uint8_t res;

    SI446X_ATOMIC {
      /* clear cs on entry prior to set,  make sure a reasonable state */
      call HW.si446x_clr_cs();
      call HW.si446x_set_cs();
      call FastSpiByte.splitWrite(SI446X_CMD_READ_CMD_BUFF);
      call FastSpiByte.splitReadWrite(0);
      res = call FastSpiByte.splitRead();
      call HW.si446x_clr_cs();
    }
    return res;
  }

  /**************************************************************************/
  /*
   * ll_si446x_get_cts
   *
   * encapsulate obtaining the current CTS value.
   *
   * CTS can be on a h/w pin or can be obtained via the SPI
   * bus.  This routine hides how it is obtained.
   */
  bool ll_si446x_get_cts() {
    bool    cts_s;
#ifdef SI446X_HW_CTS
    cts_s = call HW.si446x_cts();
    return cts_s;
#else
    cts_s = ll_si446x_get_sw_cts();
    return cts_s;
#endif
  }

   
  /**************************************************************************/
  /*
   * ll_si446x_read_frr             (low level)
   *
   * read Fast Response Register.
   * input parameter selects one of four.
   */
  uint8_t ll_si446x_read_frr(uint8_t which) { 
    uint8_t result;

    SI446X_ATOMIC {
      call HW.si446x_clr_cs();             // make sure reasonable state
      call HW.si446x_set_cs();
      call FastSpiByte.splitWrite(which);  // which one is the input parameter
      result = call FastSpiByte.splitReadWrite(0);
      result = call FastSpiByte.splitRead();
      call HW.si446x_clr_cs();
    }
    return result;
  }


  /**************************************************************************/
  /*
   * ll_si446x_trace_radio_pend     {low level)
   *
   * trace current radio interrupt status and hardware related pin state
   */
  void ll_si446x_trace_radio_pend(uint8_t *pend) {
    rps_t *rpp;
    rps_t *ppp;
    uint8_t cts, irqn, csn;
    uint8_t state, ph, modem, rssi, pmodem;

    rpp  = &rps[rps_next];
    ppp  = &rps[rps_prev];

    cts  = ll_si446x_get_cts();
    irqn = call HW.si446x_irqn();
    csn  = call HW.si446x_csn();

    /* we don't care about modem:invalid preamble
     */
    state = pend[0];
    ph    = pend[1];
    rssi  = pend[3];
    modem  = pend[2] & 0xfb;
    pmodem = ppp->modem & 0xfb;

    if ((cts == ppp->cts) && (irqn == ppp->irqn) && (csn == ppp->csn) &&
        (state == ppp->ds) && (ph == ppp->ph) &&
        (modem == pmodem) && (rssi == ppp->rssi)) {
      return;
    }

    modem = pend[2];                    /* trace actual values */
    rssi  = pend[3];
    rpp->ts = call LocalTime.get();
    rpp->cts   = cts;
    rpp->irqn  = irqn;
    rpp->csn   = csn;
    rpp->ds    = state;
    rpp->ph    = ph;
    rpp->modem = modem;
    rpp->rssi  = rssi;

    rps_prev = rps_next;
    if (++rps_next >= RPS_MAX)
      rps_next = 0;
  }


  /**************************************************************************/
  /*
   * ll_si446x_read_fast_status    (low level)
   *
   * reads status of important chip information via the FRR mechanism.
   * input is a pointer to uint8_t xyz[4] buffer
   *
   * CTS does not need to be true.
   */
  void ll_si446x_read_fast_status(void *s) {
    uint8_t *p;

    p = (uint8_t *) s;
    SI446X_ATOMIC {
      call HW.si446x_set_cs();
      call FastSpiByte.splitWrite(SI446X_CMD_FRR_A);
      call FastSpiByte.splitReadWrite(0);
      p[0] = call FastSpiByte.splitReadWrite(0);
      p[1] = call FastSpiByte.splitReadWrite(0);
      p[2] = call FastSpiByte.splitReadWrite(0);
      p[3] = call FastSpiByte.splitRead();
      call HW.si446x_clr_cs();
    }
  }
   

  /**************************************************************************/
  /*
   * ll_si446x_send_cmd      (low level)
   *
   * send a command to the radio chip
   *
   * c:         pointer to buffer to send
   * response:  pointer to response bytes if any
   * cl:        length of cmd (buffer)
   * 
   */
  void ll_si446x_send_cmd(const uint8_t *c, uint8_t *response, uint16_t cl) {
    uint16_t      t0, t1;
    cmd_timing_t *ctp;
    uint8_t       cmd;
    bool          done;

    cmd = c[0];
    ctp = &cmd_timings[cmd];
    ctp->cmd = cmd;
    done = 0;
    while (1) {
      t0 = call Platform.usecsRaw();
      t1 = t0;
      while (!ll_si446x_get_cts()) {
        t1 = call Platform.usecsRaw();
        if ((t1-t0) > SI446X_CTS_TIMEOUT) {
          done = ll_si446x_get_sw_cts();
          __PANIC_RADIO(2, t1, t0, t1-t0, done);
        }
      }
      SI446X_ATOMIC {
        /*
         * first make sure we still have CTS.  It is possible that
         * someone (mr. interupt) got in and did something that made
         * us busy.  Truely paranoid code but if we ever hit this
         * window the failure is truely nasty.  And it is possible.
         * close to 0 but not zero.
         */
        if (ll_si446x_get_cts()) {
          t1 = call Platform.usecsRaw();
          ctp->t_cts0 = t1 - t0;
          t0 = t1;
          call HW.si446x_set_cs();
          call SpiBlock.transfer((void *) c, response, cl);
          call HW.si446x_clr_cs();
          t1 = call Platform.usecsRaw();
          done = TRUE;
        }
      }
      if (done)
        break;

      /*
       * oops.  if we get here someone grabbed the channel (mr. interrupt)
       * so go try again to make sure the radio is okay to take another big one.
       */
    }
    ctp->t_cmd0 = t1 - t0;
    ctp->d_len0 = cl;
  }


  /**************************************************************************/
  /*
   * ll_si446x_get_reply        (low level)
   *
   * get chip data returned in response to last command.
   */
  void ll_si446x_get_reply(uint8_t *r, uint16_t l, uint8_t cmd) {
    uint8_t rcts;
    uint16_t t0, t1;
    cmd_timing_t *ctp;

    ctp = &cmd_timings[cmd];
    t0 = call Platform.usecsRaw();
    while (!ll_si446x_get_cts()) {
      t1 = call Platform.usecsRaw();
      if ((t1-t0) > SI446X_CTS_TIMEOUT) {
        __PANIC_RADIO(4, t1, t0, t1-t0, 0);
      }
    }
    t1 = call Platform.usecsRaw();
    ctp->t_cts_r = t1 - t0;
    t0 = t1;
    SI446X_ATOMIC {
      call HW.si446x_set_cs();
      call FastSpiByte.splitWrite(SI446X_CMD_READ_CMD_BUFF);
      call FastSpiByte.splitReadWrite(0);
      rcts = call FastSpiByte.splitRead();
      if (rcts != 0xff) {
        __PANIC_RADIO(5, rcts, 0, 0, 0);
      }
      call SpiBlock.transfer(NULL, r, l);
      call HW.si446x_clr_cs();
    }
    t1 = call Platform.usecsRaw();
    ctp->t_reply = t1 - t0;
    ctp->d_reply_len = l + 2;
  }


  /**************************************************************************/
  /*
   * ll_si446x_cmd_reply        (low level)
   *
   * perform combined send_cmd and get_reply operations.
   */
  void ll_si446x_cmd_reply(const uint8_t *cp, uint16_t cl, uint8_t *rp, uint16_t rl) {
    uint16_t t0, t1;
    cmd_timing_t *ctp;

    ctp = &cmd_timings[cp[0]];
    SI446X_ATOMIC {                     /* checkfor tasklet protection */
      t0 = call Platform.usecsRaw();
      ll_si446x_send_cmd(cp, rsp, cl);
      ll_si446x_get_reply(rp, rl, cp[0]);
      t1 = call Platform.usecsRaw();
      ll_si446x_read_fast_status(ctp->frr);
    }
    ctp->t_elapsed = t1 - t0;
  }


  /**************************************************************************/
#ifdef notdef
  /*
   * ll_si446x_getclr_all_state
   *
   * get/clr all chip state.
   * clr all pendings and return previous state in *allp.
   * we grab and clear each of the individual blocks then grab int_status
   * without doing any additional clears.
   *
   * This is debug code for observing most of the chip state.
   */

  void ll_si446x_getclr_all_state(volatile si446x_chip_all_t *allp) {
    uint8_t pends[4];

    ll_si446x_cmd_reply(si446x_int_clr, sizeof(si446x_int_clr),
                        (void *) &allp->ints, SI446X_INT_STATUS_REPLY_SIZE);
    ll_si446x_cmd_reply(si446x_ph_status_nc, sizeof(si446x_ph_status_nc),
                        (void *) &allp->ph, SI446X_PH_STATUS_REPLY_SIZE);
    ll_si446x_cmd_reply(si446x_modem_status_nc, sizeof(si446x_modem_status_nc),
                        (void *) &allp->modem, SI446X_MODEM_STATUS_REPLY_SIZE);
    ll_si446x_cmd_reply(si446x_chip_status_nc, sizeof(si446x_chip_status_nc),
                        (void *) &allp->chip, SI446X_CHIP_STATUS_REPLY_SIZE);
    pends[DEVICE_STATE] = ll_si446x_read_frr(SI446X_GET_DEVICE_STATE);
    pends[PH_STATUS]    = allp->ph.pend;
    pends[MODEM_STATUS] = allp->modem.pend;
    pends[LATCHED_RSSI] = allp->modem.latched_rssi;
    ll_si446x_trace_radio_pend(pends);
  }
#endif


  /**************************************************************************/
  /*
   * get current chip state -> *allp
   *
   * This is debug code for observing most of the chip state.
   */
  void ll_si446x_get_all_state(volatile si446x_chip_all_t *allp) {
    uint8_t pends[4];

    ll_si446x_cmd_reply(si446x_ph_status_nc, sizeof(si446x_ph_status_nc),
                        (void *) &allp->ph, SI446X_PH_STATUS_REPLY_SIZE);
    ll_si446x_cmd_reply(si446x_modem_status_nc, sizeof(si446x_modem_status_nc),
                        (void *) &allp->modem, SI446X_MODEM_STATUS_REPLY_SIZE);
    ll_si446x_cmd_reply(si446x_chip_status_nc, sizeof(si446x_chip_status_nc),
                        (void *) &allp->chip, SI446X_CHIP_STATUS_REPLY_SIZE);
    ll_si446x_cmd_reply(si446x_int_status_nc, sizeof(si446x_int_status_nc),
                        (void *) &allp->ints, SI446X_INT_STATUS_REPLY_SIZE);
    pends[DEVICE_STATE] = ll_si446x_read_frr(SI446X_GET_DEVICE_STATE);
    pends[PH_STATUS]    = allp->ph.pend;
    pends[MODEM_STATUS] = allp->modem.pend;
    pends[LATCHED_RSSI] = allp->modem.latched_rssi;
    ll_si446x_trace_radio_pend(pends);
  }


  /**************************************************************************/
  /*
   * ll_si446x_check_weird
   *
   * check for abnormal conditions when performing radio chip operations.
   */
  void ll_si446x_check_weird(uint8_t *status) {
    if ((status[PH_STATUS]    & 0xC0) ||
        (status[MODEM_STATUS] & 0x50)) {
      ll_si446x_get_all_state(&chip_debug);
      __PANIC_RADIO(98, status[DEVICE_STATE], status[PH_STATUS],
                    status[MODEM_STATUS], 0);
      ll_si446x_get_all_state(&chip_debug);
      nop();
    }
  }


  /**************************************************************************/
  /*
   * readBlock
   * pullBlock
   * writeBlock
   *
   * Basic SPI Access Routines
   */

  /* read from the SPI, putting bytes in buf
   */
  void readBlock(uint8_t *buf, uint8_t count) {
    uint8_t i;

    for (i = 0; i < count-1; i++)
      buf[i] = call FastSpiByte.splitReadWrite(0);
    buf[i] = call FastSpiByte.splitRead();
  }

  /* pull bytes from the SPI, throwing them away
   */
  void pullBlock(uint8_t count) {
    uint8_t i;

    for (i = 1; i < count; i++)
      call FastSpiByte.splitReadWrite(0);
    call FastSpiByte.splitRead();
  }

  /* write bytes from buf to the SPI
   */
  void writeBlock(uint8_t *buf, uint8_t count) {
    uint8_t i;

    for (i = 0; i < count; i++)
      call FastSpiByte.splitReadWrite(buf[i]);
    call FastSpiByte.splitRead();
  }


  /**************************************************************************/
  /*
   * ll_446x_dump_radio_fifo
   *
   * It is unclear if dumping the FIFO is a) possible or b) useful.
   */
  void ll_i446x_dump_radio_fifo() {
    uint8_t cts, rx_count, tx_count;
    /*
     * CSn (NSEL), needs to be held high (deasserted, cleared) for 80ns.
     * We throw a nop in just to make sure it stays up long enough.
     * Usually it isn't a problem but dump has a back to back because
     * we don't know the state of CS when called.
     */
    call HW.si446x_clr_cs();
    nop();
    SI446X_ATOMIC {
      call HW.si446x_set_cs();
      call FastSpiByte.splitWrite(SI446X_CMD_FIFO_INFO);
      call FastSpiByte.splitReadWrite(0);
      call FastSpiByte.splitRead();
      /* response
       */
      call FastSpiByte.splitWrite(0);
      cts = call FastSpiByte.splitReadWrite(0);           /* CTS */
      rx_count = call FastSpiByte.splitReadWrite(0);      /* RX_FIFO_CNT */
      tx_count = call FastSpiByte.splitRead();            /* TX_FIFO_CNT */
      call HW.si446x_clr_cs();
    }

    /*
     * how to figure out if it is a tx or rx in the fifo.  So
     * we can pull the fifo contents.  Do we need to look at the
     * radio state to see what is going on?
     */
    if (tx_count < rx_count)
      tx_count = rx_count;
  }


  /**************************************************************************/
  /*
   * ll_si446x_dump_properties
   *
   * read and save all relevant properties from radio chip.
   */
  void ll_si446x_dump_properties() {
    const dump_prop_desc_t *dpp;
    cmd_timing_t *ctp, *ctp_ff;
    uint8_t group, index, length;
    uint8_t  *w, wl;                    /* working */
    uint16_t t0, t1, tot0;

    ctp_ff = &cmd_timings[0xff];
    t0 = call Platform.usecsRaw();
    while (!ll_si446x_get_cts()) {
      t1 = call Platform.usecsRaw();
      if ((t1-t0) > SI446X_CTS_TIMEOUT) {
        __PANIC_RADIO(8, t1, t0, t1-t0, 0);
      }
    }
    t1 = call Platform.usecsRaw();
    dpp = &dump_prop[0];
    while (dpp->where) {
      group = dpp->prop_id >> 8;
      index = dpp->prop_id & 0xff;
      length = dpp->length;
      w = dpp->where;
      t0 = call Platform.usecsRaw();
      tot0 = t0;
      ctp = &prop_timings[group];
      memset(ctp, 0, sizeof(*ctp));
      ctp->cmd = group;

      while (length) {
        t0 = call Platform.usecsRaw();
        if (!ll_si446x_get_cts()) {
          __PANIC_RADIO(8, 0, 0, 0, 0);
        }      
        t1 = call Platform.usecsRaw();
        ctp->t_cts0 += t1 - t0;

        wl = (length > 16) ? 16 : length;
        t0 = call Platform.usecsRaw();
        SI446X_ATOMIC {
          call HW.si446x_set_cs();
          call FastSpiByte.splitWrite(SI446X_CMD_GET_PROPERTY);
          call FastSpiByte.splitReadWrite(group);
          call FastSpiByte.splitReadWrite(wl);
          call FastSpiByte.splitReadWrite(index);
          call FastSpiByte.splitRead();
          call HW.si446x_clr_cs();
          t1 = call Platform.usecsRaw();
          ctp->t_cmd0 += t1 - t0;
          ctp->d_len0 += 4;

          ll_si446x_get_reply(w, wl, 0xff);
        }
        ctp->t_cts_r     += ctp_ff->t_cts_r;
        ctp->t_reply     += ctp_ff->t_reply;
        ctp->d_reply_len += ctp_ff->d_reply_len;
        length -= wl;
        index += wl;
        w += wl;
      }
      t1 = call Platform.usecsRaw();
      ctp->t_elapsed = t1 - tot0;
      nop();
      ll_si446x_read_fast_status(ctp->frr);
      dpp++;
    }
  }


  /**************************************************************************/
  /*
   * ll_si446x_dump_radio
   *
   * dump full radio configuration and state.
   */
  void ll_si446x_drf() {

    SI446X_ATOMIC {
      rd.p_dump_start = call Platform.usecsRaw();
      rd.l_dump_start = call LocalTime.get();

      /* do CSN before we reset the SPI port */
      rd.CSN_pin     = call HW.si446x_csn();
      rd.CTS_pin     = call HW.si446x_cts();
      rd.IRQN_pin    = call HW.si446x_irqn();
      rd.SDN_pin     = call HW.si446x_sdn();

      call HW.si446x_clr_cs();          /* reset SPI on chip */
      nop();
      call HW.si446x_set_cs();
      nop();
      call HW.si446x_clr_cs();

      rd.ta0ccr3     = TA0CCR3;
      rd.ta0cctl3    = TA0CCTL3;

      nop();                              /* these should become ll_* */
      ll_si446x_cmd_reply(si446x_part_info, sizeof(si446x_part_info),
                          (void *) &rd.part_info, SI446X_PART_INFO_REPLY_SIZE);

      ll_si446x_cmd_reply(si446x_func_info, sizeof(si446x_func_info),
                          (void *) &rd.func_info, SI446X_FUNC_INFO_REPLY_SIZE);

      ll_si446x_cmd_reply(si446x_gpio_cfg_nc, sizeof(si446x_gpio_cfg_nc),
                          (void *) &rd.gpio_cfg, SI446X_GPIO_CFG_REPLY_SIZE);

      ll_si446x_cmd_reply(si446x_fifo_info_nc, sizeof(si446x_fifo_info_nc),
                          rsp, SI446X_FIFO_INFO_REPLY_SIZE);
      rd.rxfifocnt  = rsp[0];
      rd.txfifofree = rsp[1];

      ll_si446x_cmd_reply(si446x_ph_status_nc, sizeof(si446x_ph_status_nc),
                          (void *) &rd.ph_status, SI446X_PH_STATUS_REPLY_SIZE);

      ll_si446x_cmd_reply(si446x_modem_status_nc, sizeof(si446x_modem_status_nc),
                          (void *) &rd.modem_status, SI446X_MODEM_STATUS_REPLY_SIZE);

      ll_si446x_cmd_reply(si446x_chip_status_nc, sizeof(si446x_chip_status_nc),
                          (void *) &rd.chip_status, SI446X_CHIP_STATUS_REPLY_SIZE);

      ll_si446x_cmd_reply(si446x_int_status_nc, sizeof(si446x_int_status_nc),
                          (void *) &rd.int_state, SI446X_INT_STATUS_REPLY_SIZE);

      ll_si446x_cmd_reply(si446x_device_state, sizeof(si446x_device_state),
                          rsp, SI446X_DEVICE_STATE_REPLY_SIZE);
      rd.device_state = rsp[0];
      rd.channel      = rsp[1];

      ll_si446x_read_fast_status(rd.frr);

      ll_si446x_cmd_reply(si446x_packet_info_nc, sizeof(si446x_packet_info_nc),
                          (void *) &rd.packet_info_len, SI446X_PACKET_INFO_REPLY_SIZE);

      nop();
      ll_si446x_dump_properties();
      nop();
      rd.l_dump_end = call LocalTime.get();
      rd.l_delta =  rd.l_dump_end - rd.l_dump_start;
    }
  }


  /**************************************************************************/
  /*
   * Si446xCmd.get_packet_info
   *
   * get packet_info for last received packet.
   * returns variable length field value (length) from last rx packet.
   * we do not override and fields length (that's just weird).
   */
  async command uint16_t Si446xCmd.get_packet_info() {
    uint8_t r[2];

    call Si446xCmd.cmd_reply(si446x_packet_info_nc, sizeof(si446x_packet_info_nc), r, 2);
    return r[0] << 8 | r[1];
  }


  /**************************************************************************/
  /*
   * Si446xCmd.read_rx_fifo
   *
   * read data bytes from the TXFIFO.
   * First it sets CS which resets the radio SPI and enables
   * the SPI subsystem, next the cmd SI446X_CMD_RX_FIFO_READ
   * and then we pull data from the FIFO across the SPI bus.
   * CS is deasserted which terminates the block.
   *
   * If we pull too many bytes from the RX fifo, the chip will
   * throw an FIFO Underflow exception.
   */
  async command void Si446xCmd.read_rx_fifo(uint8_t *data, uint8_t length) {
    uint16_t t0, t1;

    SI446X_ATOMIC {
      t0 = call Platform.usecsRaw();
      call HW.si446x_set_cs();
      call FastSpiByte.splitWrite(SI446X_CMD_RX_FIFO_READ);
      call FastSpiByte.splitReadWrite(0);
      readBlock(data, length);
      call HW.si446x_clr_cs();
      t1 = call Platform.usecsRaw();
      nop();
    }
    t1 -= t0;
  }


  /**************************************************************************/
  /*
   * write_tx_fifo
   *
   * sends data bytes into the TXFIFO.
   * First it sets CS which resets the radio SPI and enables
   * the SPI subsystem, next the cmd SI446X_CMD_TX_FIFO_WRITE
   * is sent followed by the data.  After the data is sent
   * CS is deasserted which terminates the block.
   *
   * If the TX fifo gets full, an additional write will throw a
   * FIFO Overflow exception.
   */
  async command void Si446xCmd.write_tx_fifo(uint8_t *data, uint8_t length) {
    uint16_t t0, t1;

    SI446X_ATOMIC {
      t0 = call Platform.usecsRaw();
      call HW.si446x_set_cs();
      call FastSpiByte.splitWrite(SI446X_CMD_TX_FIFO_WRITE);
      writeBlock(data, length);
      call HW.si446x_clr_cs();
      t1 = call Platform.usecsRaw();
      nop();
      t1 -= t0;
    }
  }


  /**************************************************************************/
  /*
   * Si446xCmd.ll_clr_ints
   * Si446xCmd.ll_getclr_ints
   *
   * clear chip interrupt pending status.
   * alternately method reads current status as well.
   */
  async command void Si446xCmd.ll_clr_ints() {
    ll_si446x_send_cmd(si446x_int_clr, rsp, sizeof(si446x_int_clr));
  }
  /*
   * get/clr interrupt state
   * clr all pendings and return previous state in *intp
   */
  async command void Si446xCmd.ll_getclr_ints(volatile si446x_int_state_t *intp) {
    ll_si446x_cmd_reply(si446x_int_clr, sizeof(si446x_int_clr),
                        (void *) intp, SI446X_INT_STATUS_REPLY_SIZE);
  }


  /**************************************************************************/
  /*
   * ll_wait_for_cts
   *
   * wait for the radio chip to report that it is ready for the next command.
   */
  bool ll_wait_for_cts() {
    uint16_t t0, t1;
    t0 = call Platform.usecsRaw();
    t1 = t0;
    while (!ll_si446x_get_cts()) {
      t1 = call Platform.usecsRaw();
      ll_si446x_read_fast_status(radio_pend);
      if ((t1-t0) > SI446X_CTS_TIMEOUT) {
        ll_si446x_read_fast_status(radio_pend1);
        ll_si446x_drf();
	__PANIC_RADIO(24, t1, t0, t1-t0, 0);
        ll_si446x_read_fast_status(radio_pend);
	return FALSE;
      }
    }
    ll_si446x_read_fast_status(radio_pend);
    return TRUE;
  }


  /**************************************************************************/
  /*
   * HW.interrupt
   */
  async event void HW.si446x_interrupt() {
    signal Si446xCmd.interrupt();
  }


  /**************************************************************************/
  /*
   * Si446xCmd.clr_cs
   */
  async command void          Si446xCmd.clr_cs() {
    call HW.si446x_clr_cs();
  }


  /**************************************************************************/
  /*
   * Si446xCmd.shutdown
   */
  async command void          Si446xCmd.shutdown() {
    call HW.si446x_shutdown();
  }


  /**************************************************************************/
  /*
   * Si446xCmd.unshutdown
   */
  async command void         Si446xCmd.unshutdown() {
    call HW.si446x_unshutdown();
  }


  /**************************************************************************/
  /*
   * Si446xCmd.disbleInterrupt
   */
  async command void          Si446xCmd.disableInterrupt() {
    call HW.si446x_disableInterrupt();
  }

  /**************************************************************************/
  /*
   * Si446xCmd.enableInterrupt
   */
  async command void          Si446xCmd.enableInterrupt() {
    call HW.si446x_enableInterrupt();
  }


  /**************************************************************************/
  /*
   * Si446xCmd.get_cts
   *
   * encapsulate obtaining the current CTS value.
   *
   * CTS can be on a h/w pin or can be obtained via the SPI
   * bus.  This routine hides how it is obtained.
   */
  async command bool Si446xCmd.get_cts() {
       return ll_si446x_get_cts();
  }


  /**************************************************************************/
  /*
   * Si446xCmd.get_config_lists()
   *
   * return the list of config lists to be used to configure the 446x chip.
   * since configuration is a long process (around 10ms), the list is processed
   * by the a separate task managed by the driver.
   */
  const uint8_t *config_list[] = {si446x_wds_config, si446x_local_config, NULL};

  async command uint8_t ** Si446xCmd.get_config_lists() {
    nop();
    call Trace.trace(T_R_RX_RECV, 0, 0);
    return (uint8_t **) config_list;
  }


  /**************************************************************************/
  /*
   * Si446xCmd.fast_device_state
   * uint8_t Si446xCmd.fast_ph_pend
   * Si446xCmd.fast_modem_pend
   * Si446xCmd.fast_latched_rssi
   *
   * read Fast Response Register. 
   * register comes back on the same SPI transaction as the command.
   * CTS does not need to be true.
   * 
   */
  async command uint8_t Si446xCmd.fast_device_state() {
    return ll_si446x_read_frr(SI446X_GET_DEVICE_STATE);
  }

  async command uint8_t Si446xCmd.fast_ph_pend() {
    return ll_si446x_read_frr(SI446X_GET_PH_PEND);
  }

  async command uint8_t Si446xCmd.fast_modem_pend() {
    return ll_si446x_read_frr(SI446X_GET_MODEM_PEND);
  }

  async command uint8_t Si446xCmd.fast_latched_rssi() {
    return ll_si446x_read_frr(SI446X_GET_LATCHED_RSSI);
  }


  /**************************************************************************/
  /*
   * Si446xCmd.check_CCA
   *
   * check the 'clear channel assessment' condition. denotes if our receiver
   * is detecting an incoming radio signal of sufficient strength to denote
   * channel is occupied.
   * returns true if channel is assessed as clear (low RSSI value)
   */
  async command bool Si446xCmd.check_CCA() {
    uint8_t rssi;

    rssi = call Si446xCmd.fast_latched_rssi();
    if (rssi < si446x_cca_threshold)
      return TRUE;
    return FALSE;
  }


  /**************************************************************************/
  /*
   * Si446xCmd.config_frr
   *
   * send a block of configuration data to the radio.  Each block is
   * is made up of multiple commands, (size, command data, starts with
   * command to send), terminated by 0.
   */
  async command void Si446xCmd.config_frr() {
    call Si446xCmd.send_cmd(si446x_frr_config, rsp, sizeof(si446x_frr_config));
  }


  /**************************************************************************/
  /*
   * Si446xCmd.read_property
   *
   * read property of radio chip
   */
  async command void Si446xCmd.read_property(uint16_t p_id, uint16_t num, uint8_t *w) {
    uint8_t group, index;

    group = p_id >> 8;
    index = p_id & 0xff;
    SI446X_ATOMIC {
      call HW.si446x_set_cs();
      call FastSpiByte.splitWrite(SI446X_CMD_GET_PROPERTY);
      call FastSpiByte.splitReadWrite(group);
      call FastSpiByte.splitReadWrite(num);
      call FastSpiByte.splitReadWrite(index);
      call FastSpiByte.splitRead();
      call HW.si446x_clr_cs();
      ll_si446x_get_reply(w, num, 0xff);
    }
  }


  /**************************************************************************/
  /*
   * Si446xCmd.dump_radio
   */
  async command void Si446xCmd.dump_radio() {
    atomic {
      ll_si446x_drf();
    }
  }


   /**************************************************************************/
  /*
   * Si446xCmd.send_cmd
   * Si446xCmd.get_reply
   * Si446xCmd.cmd_reply
   *
   * send command, get response, or perform both operations on radio chip.
   */
  async command void Si446xCmd.send_cmd(const uint8_t *c, uint8_t *response, uint16_t length) {
    ll_si446x_send_cmd(c, response, length);
    ll_si446x_read_fast_status(radio_pend);
  }

  async command void Si446xCmd.get_reply(uint8_t *r, uint16_t l, uint8_t cmd) {
    ll_si446x_get_reply(r, l, cmd);
    ll_si446x_read_fast_status(radio_pend);
  }

  async command void Si446xCmd.cmd_reply(const uint8_t *cp, uint16_t cl, uint8_t *rp, uint16_t rl) {
    uint16_t t0, t1;
    cmd_timing_t *ctp;

    ctp = &cmd_timings[cp[0]];
    t0 = call Platform.usecsRaw();
    ll_si446x_send_cmd(cp, rsp, cl);
    ll_si446x_get_reply(rp, rl, cp[0]);
    t1 = call Platform.usecsRaw();
    ctp->t_elapsed = t1 - t0;
    ll_si446x_read_fast_status(ctp->frr);
  }


  /**************************************************************************/
  /*
   * Si446xCmd.set_property
   *
   * read a single property from the radio chip
   */
  async command void Si446xCmd.set_property(uint16_t prop, uint8_t *values, uint16_t vl) {
    uint8_t prop_buf[16];
    uint16_t i;

    prop_buf[0] = SI446X_CMD_SET_PROPERTY;
    prop_buf[1] = prop >> 8;            /* group */
    prop_buf[2] = vl;                   /* num_props */
    prop_buf[3] = prop & 0xff;          /* start_prop */

    for (i = 0; i < 12 && i < vl; i++ )
      prop_buf[i+4] = values[i];
    call Si446xCmd.send_cmd(prop_buf, rsp, vl+4);
  }


  /**************************************************************************/
  /*
   * Si446xCmd.start_tx
   *
   * send the start command to the radio chip.
   * input parameter specifies length of packet to transmit
   */
  async command void Si446xCmd.start_tx(uint16_t len) {
    uint8_t x[5];

    x[0] = SI446X_CMD_START_TX;
    x[1] = 0;                     /* channel */
    x[2] = 0x30;                  /* back to READY */
    x[3] = 0;
    x[4] = len & 0xff;
    ll_si446x_drf();
    nop();
    call Si446xCmd.send_cmd((void *) x, rsp, 5);
    ll_wait_for_cts();
 }

  /**************************************************************************/
  /*
   * Si446xCmd.start_rx
   *
   * start the Receiver using specified parameters
   *
   */
  async command void Si446xCmd.start_rx() {
    call Si446xCmd.send_cmd(start_rx_cmd, rsp, sizeof(start_rx_cmd));
    ll_wait_for_cts();                    // wait for rx start up
  }


  /**************************************************************************/
  /*
   * Si446xCmd.start_rx_short
   *
   * start receiver using settings from previous start_rx operation
   *
   */
  async command void Si446xCmd.start_rx_short() {
    call Si446xCmd.send_cmd(start_rx_short_cmd, rsp, sizeof(start_rx_short_cmd));
  }


  /**************************************************************************/
  /*
   * Si446xCmd.power_up
   *
   * tell the radio chip to power up
   *
   */
  async command void Si446xCmd.power_up() {
    call Si446xCmd.send_cmd(si446x_power_up, rsp, sizeof(si446x_power_up));
  }


  /**************************************************************************/
  /*
   * Si446xCmd.change_state
   *
   * Force radio chip to the specified state.
   *
   * @param     state       new state to enter
   *
   * @return    final state achieved
   */

  async command Si446x_device_state_t Si446xCmd.change_state(Si446x_device_state_t state, bool wait) {
    uint8_t cmd[2];

    cmd[0] = SI446X_CMD_CHANGE_STATE;
    cmd[1] = state;                          // new state
    call Si446xCmd.send_cmd(cmd, rsp, sizeof(cmd));
    if (wait)
      ll_wait_for_cts();           // wait for command to complete
    return call Si446xCmd.fast_device_state();
  }


  /**************************************************************************/
  /*
   * Si446xCmd.fifo_info
   *
   * retreive current receive/transmit fifo status and optionally flush.
   * can pass null pointers for status if just flushing.
   * individual flags specify whether to flush one, both, or neither fifo.
   */
  async command void Si446xCmd.fifo_info(uint16_t *rxp, uint16_t *txp, uint8_t flush_bits) {
    uint8_t flusher[2], fifo_cnts[2];

    flusher[0] = SI446X_CMD_FIFO_INFO;
    flusher[1] = flush_bits;
    ll_si446x_cmd_reply(flusher, 2, fifo_cnts, 2);
    ll_wait_for_cts();
    if (rxp)
      *rxp = fifo_cnts[0];
    if (txp)
      *txp = fifo_cnts[1];
  }


  /**************************************************************************/
  /*
   * Si446xCmd.fast_all
   *
   * read the fast status registers.
   * trace the status and check for abnormal conditions.
   */
  async command void Si446xCmd.fast_all(uint8_t *status) {
    ll_si446x_read_fast_status(status);
    ll_si446x_trace_radio_pend(status);
    ll_si446x_check_weird(status);
  }


  /**************************************************************************/
  /*
   * Si446xCmd.trace_radio_pend
   *
   * trace current radio interrupt status and hardware related pin state
   */
  async command void Si446xCmd.trace_radio_pend(uint8_t *pend) {
    ll_si446x_trace_radio_pend(pend);
  }


  /**************************************************************************/
  /*
   * Panic.hook
   *
   * handles collection of useful informtion when a panic occurs.
   */
  async event void Panic.hook() { }

}
