COMPONENT=testGPSC

# PFLAGS += -DTESTGPSP_RESET_CAPTURE_RESET
# PFLAGS += -DDISABLE_GPS_SYSBOOT

OPTFLAGS = -ggdb -Os -fnesc-no-inline
#OPTFLAGS = -O0 -ggdb -fnesc-no-inline

TINYOS_ROOT_DIR ?= ../..
include $(TINYOS_ROOT_DIR)/Makefile.include
