COMPONENT=testGPSC

# PFLAGS += -DTESTGPSP_RESET_CAPTURE_RESET
PFLAGS += -DGPS_EAVESDROP

OPTFLAGS = -ggdb -Os -fnesc-no-inline
#OPTFLAGS = -O0 -ggdb -fnesc-no-inline

TINYOS_ROOT_DIR ?= ../..
include $(TINYOS_ROOT_DIR)/Makefile.include
