#ifndef __SI446X_CONFIG_WDS_H__
#define __SI446X_CONFIG_WDS_H__

/*
 * Copyright (c) 2016-2018 Eric B. Decker, Daniel J. Maltbie
 * All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 * See COPYING in the top level directory of this source tree.
 *
 * Contact: Eric B. Decker <cire831@gmail.com>
 *          Daniel J. Maltbie <dmaltbie@daloma.org>
 *
 * Author: Eric B. Decker
 * Date: 1/15/2016
 * Author: Daniel J. Maltbie <dmaltbie@daloma.org>
 * Date: 5/20/2017
 */

/* define list of pstrings (byte array( and initialize it with
 * the configuration generated by the WDS3 program
 * Include one of the pre-defined configuration files
 */

#define WDS_FILENAME  "Si4468_10kb_434m_200khz"
#include "WDS-files/Si4468_10kb_434m_200khz/src/application/radio_config.h"

#ifdef not_defined
#define WDS_FILENAME  "Si4468_100b_433m_200khz_psm"
#include "WDS-files/Si4468_100b_433m_200khz_psm/src/application/radio_config.h"

#define WDS_FILENAME  "Si4468_10kb_433m_200khz"
#include "WDS-files/Si4468_10kb_433m_200khz/src/application/radio_config.h"

#define WDS_FILENAME  "Si4468_10kb_433m_200khz_psm"
#include "WDS-files/Si4468_10kb_433m_200khz_psm/src/application/radio_config.h"

#define WDS_FILENAME  "Si4468_30kb_433m_200khz"
#include "WDS-files/Si4468_1kb_433m_200khz/src/application/radio_config.h"

#define WDS_FILENAME  "Si4468_40kb_433m_200khz"
#include "WDS-files/Si4468_40kb_433m_200khz/src/application/radio_config.h"

#define WDS_FILENAME  "Si4468_50kb_433m_200khz"
#include "WDS-files/Si4468_50kb_433m_200khz/src/application/radio_config.h"

#define WDS_FILENAME  "Si4468_80kb_433m_200khz"
#include "WDS-files/Si4468_80kb_433m_200khz/src/application/radio_config.h"

#define WDS_FILENAME  "Si4468_100kb_433m_200khz"
#include "WDS-files/Si4468_100kb_433m_200khz/src/application/radio_config.h"
#endif

const uint8_t si446x_wds_config[] = RADIO_CONFIGURATION_DATA_ARRAY;

#endif          //__SI446X_CONFIG_WDS_H__
