
/*
 * code auto-generated by wds_prep.py
*/

#include <stdint.h>
#include <stdlib.h>

extern uint8_t const SI4468_10KB_433M_200KHZ_config[];
extern uint8_t const SI4468_10KB_433M_200KHZ_name[];
extern uint8_t const SI4468_100B_433M_200KHZ_PSM_config[];
extern uint8_t const SI4468_100B_433M_200KHZ_PSM_name[];
extern uint8_t const SI4468_100KB_433M_200KHZ_config[];
extern uint8_t const SI4468_100KB_433M_200KHZ_name[];
extern uint8_t const SI4468_10KB_433M_200KHZ_PSM_config[];
extern uint8_t const SI4468_10KB_433M_200KHZ_PSM_name[];

// const array of const strings, required definition and syntax
const uint8_t *const wds_radio_configs[] = {
   SI4468_10KB_433M_200KHZ_config,
   SI4468_10KB_433M_200KHZ_name,
   SI4468_100B_433M_200KHZ_PSM_config,
   SI4468_100B_433M_200KHZ_PSM_name,
   SI4468_100KB_433M_200KHZ_config,
   SI4468_100KB_433M_200KHZ_name,
   SI4468_10KB_433M_200KHZ_PSM_config,
   SI4468_10KB_433M_200KHZ_PSM_name,
    NULL, NULL,
};



int wds_default_override  = 0;

int s_compare(uint8_t *s1, uint8_t *s2) {
    while ((*s1) && (*s2) && (*s1 != *s2)) {
        s1++;
        s2++;
    }
    if ((*s1) || (*s2))
        return 0;
    return 1;
}


const uint8_t const * const *wds_config_list() {
    return wds_radio_configs;
}

uint8_t const *wds_config_select(uint8_t *cname) {
    uint8_t *this = (void *) wds_radio_configs;
    uint8_t *pname;

    // defaulit is first in list
    if (!cname)
        return wds_radio_configs[0];

    while (this) {
        pname = this + 1;
        if (s_compare(cname, pname))
            return this;
        this += 2;
    }
    return NULL;
}
