
/*
 * code auto-generated by wds_prep.py
*/



int wds_set_default(int level);
const uint8_t const * const *wds_config_list();
uint8_t const *wds_config_select(uint8_t *cname);
const uint8_t const * const *wds_default_name();
