#!/bin/bash
# -*- mode: sh -*-
#
# Copy various gdb rc files to set up a dev6a and mm6a debugging environment.
#
# you should be in the top level of the application you are setting up for debugging.
# you must have the following defined in your environment:
#
# TINYOS_ROOT_DIR:  points to core tinyos source tree
# MM_ROOT:          points to core MamMark source tree
#
# then simply run ${MM_ROOT}/tools/00_gdb/copy_gdb

if [[ ! -v TINYOS_ROOT_DIR || ! -v MM_ROOT ]]; then
    echo -e "\n*** TINYOS_ROOT_DIR and MM_ROOT environment variables need to be defined.\n"
    exit 1
fi

if [[ -e .gdbinit ]]; then
    echo -e "\n*** .gdbinit already exists, delete if you really want to copy in new files.\n"
    exit 2
fi

echo -e "\nset -o verbose"
set -o verbose

TP_GDB=${TINYOS_ROOT_DIR}/tools/99_gdb
TP_MSP432_GDB=${TINYOS_ROOT_DIR}/tos/chips/msp432/99_gdb
MM_GDB=${MM_ROOT}/tools/00_gdb
MM_PLAT=${MM_ROOT}/tos/platforms
MM_CHIP=${MM_ROOT}/tos/chips
MM_TAGMON=${MM_ROOT}/apps/tagmon

cp ${MM_GDB}/gdbinit                 .gdbinit
cp ${MM_GDB}/gdb_mm                  .gdb_mm
cp ${TP_GDB}/gdb_tasks.py            .gdb_tasks.py
cp ${TP_GDB}/gdb_timers.py           .gdb_timers.py
cp ${TP_MSP432_GDB}/gdb_msp432       .gdb_msp432

cp ${MM_CHIP}/gsd4e_v4/gdb_gps       .gdb_gps
cp ${MM_CHIP}/gsd4e_v4/gdb_gps_hw.py .gdb_gps_hw.py
cp ${MM_CHIP}/si446x/gdb_si446x.py   .gdb_si446x.py
cp ${MM_PLAT}/mm6a/gdb_mm6a          .gdb_mm6a
cp ${MM_PLAT}/dev6a/gdb_dev6a        .gdb_dev6a
cp ${MM_PLAT}/mm/gdb_hwMm.py         .gdb_hwMm.py

cp ${MM_TAGMON}/gdb_tagmon.py        .gdb_tagmon.py

set +o verbose

echo -e "\n12 files copied.  You may want to tweak .gdbinit."
