/**
 * Copyright 2010 (c) Eric B. Decker
 * All rights reserved.
 *
 * @author Eric B. Decker
 *
 * define platform versioning and structures for representing it
 *
 *    8     8     8
 * major.minor.build
 *
 * build is an autogenerated value via make system.
 */

#ifndef _H_PLATFORM_VERSION_h
#define _H_PLATFORM_VERSION_h

#define MAJOR 0
#define MINOR 4

#endif // _H_PLATFORM_VERSION_H
