  components new      TagnetSysExecAdapterP ( TN_20_ID )  as   tn_20_Vx;
  components new      TagnetSysExecAdapterP ( TN_21_ID )  as   tn_21_Vx;
  components new         TagnetNameElementP ( TN_11_ID )  as   tn_11_Vx;
  components new       TagnetGpsXyzAdapterP ( TN_10_ID )  as   tn_10_Vx;
  components new         TagnetNameElementP ( TN_13_ID )  as   tn_13_Vx;
  components new         TagnetNameElementP ( TN_12_ID )  as   tn_12_Vx;
  components new         TagnetNameElementP ( TN_15_ID )  as   tn_15_Vx;
  components new        TagnetImageAdapterP ( TN_14_ID )  as   tn_14_Vx;
  components new      TagnetSysExecAdapterP ( TN_17_ID )  as   tn_17_Vx;
  components new         TagnetNameElementP ( TN_16_ID )  as   tn_16_Vx;
  components new      TagnetSysExecAdapterP ( TN_19_ID )  as   tn_19_Vx;
  components new      TagnetSysExecAdapterP ( TN_18_ID )  as   tn_18_Vx;
  components new         TagnetNameElementP ( TN_1_ID  )  as    tn_1_Vx;
  components                TagnetNameRootP               as    tn_0_Vx;
  components new         TagnetNameElementP ( TN_3_ID  )  as    tn_3_Vx;
  components new         TagnetNameElementP ( TN_2_ID  )  as    tn_2_Vx;
  components new      TagnetIntegerAdapterP ( TN_5_ID  )  as    tn_5_Vx;
  components new            TagnetNamePollP ( TN_4_ID  )  as    tn_4_Vx;
  components new         TagnetNameElementP ( TN_7_ID  )  as    tn_7_Vx;
  components new         TagnetNameElementP ( TN_6_ID  )  as    tn_6_Vx;
  components new         TagnetNameElementP ( TN_9_ID  )  as    tn_9_Vx;
  components new         TagnetNameElementP ( TN_8_ID  )  as    tn_8_Vx;
    tn_20_Vx.Super ->    tn_16_Vx.Sub[unique(TN_16_UQ)];
  SysNIB           =     tn_20_Vx.Adapter;
    tn_21_Vx.Super ->    tn_16_Vx.Sub[unique(TN_16_UQ)];
  SysRunning       =     tn_21_Vx.Adapter;
    tn_11_Vx.Super ->     tn_1_Vx.Sub[unique(TN_1_UQ)];
    tn_10_Vx.Super ->     tn_9_Vx.Sub[unique(TN_9_UQ)];
  InfoSensGpsXyz   =     tn_10_Vx.Adapter;
    tn_13_Vx.Super ->    tn_12_Vx.Sub[unique(TN_12_UQ)];
    tn_12_Vx.Super ->    tn_11_Vx.Sub[unique(TN_11_UQ)];
    tn_15_Vx.Super ->     tn_1_Vx.Sub[unique(TN_1_UQ)];
    tn_14_Vx.Super ->    tn_13_Vx.Sub[unique(TN_13_UQ)];
  ImageStore       =     tn_14_Vx.Adapter;
    tn_17_Vx.Super ->    tn_16_Vx.Sub[unique(TN_16_UQ)];
  SysActive        =     tn_17_Vx.Adapter;
    tn_16_Vx.Super ->    tn_15_Vx.Sub[unique(TN_15_UQ)];
    tn_19_Vx.Super ->    tn_16_Vx.Sub[unique(TN_16_UQ)];
  SysGolden        =     tn_19_Vx.Adapter;
    tn_18_Vx.Super ->    tn_16_Vx.Sub[unique(TN_16_UQ)];
  SysBackup        =     tn_18_Vx.Adapter;
     tn_1_Vx.Super ->     tn_0_Vx.Sub[unique(TN_0_UQ)];
  Tagnet           =     tn_0_Vx;
     tn_3_Vx.Super ->     tn_2_Vx.Sub[unique(TN_2_UQ)];
     tn_2_Vx.Super ->     tn_1_Vx.Sub[unique(TN_1_UQ)];
     tn_5_Vx.Super ->     tn_3_Vx.Sub[unique(TN_3_UQ)];
  PollCount        =      tn_5_Vx.Adapter;
     tn_4_Vx.Super ->     tn_3_Vx.Sub[unique(TN_3_UQ)];
  Poll             =      tn_4_Vx.Adapter;
     tn_7_Vx.Super ->     tn_6_Vx.Sub[unique(TN_6_UQ)];
     tn_6_Vx.Super ->     tn_1_Vx.Sub[unique(TN_1_UQ)];
     tn_9_Vx.Super ->     tn_8_Vx.Sub[unique(TN_8_UQ)];
     tn_8_Vx.Super ->     tn_7_Vx.Sub[unique(TN_7_UQ)];
